version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD=qwerty
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    

  go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:1323
    depends_on:
      db:
        condition: service_healthy