basePath: /
definitions:
  handler.response:
    type: object
  model.LoginRequest:
    properties:
      email:
        example: email@example.com
        type: string
      password:
        example: Password12345!
        maxLength: 50
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  model.UserRequest:
    properties:
      email:
        example: email@example.com
        type: string
      password:
        example: Password12345!
        maxLength: 50
        minLength: 8
        type: string
      username:
        example: username
        maxLength: 50
        minLength: 3
        type: string
    required:
    - email
    - password
    - username
    type: object
host: localhost:8888
info:
  contact:
    email: raitermark@proton.me
    name: Mark Raiter
  description: Docs for Blog API
  title: Blog API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Token
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Login
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register user
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User ID
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Register user
      tags:
      - auth
  /health:
    get:
      description: Healthcheck
      produces:
      - application/json
      responses:
        "200":
          description: healthy
          schema:
            $ref: '#/definitions/handler.response'
      summary: Healthcheck
      tags:
      - health
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
